#!/usr/bin/env python3
import json
from pathlib import Path

OUT = Path('output')
OUT.mkdir(exist_ok=True)

items = [
    (10,'tf2_scream_fortress','TEAM FORTRESS 2: HALLOWEEN COMEÇOU','SCREAM FORTRESS XVIII JÁ ESTÁ NO AR','https://store.steampowered.com/oldnews/?appids=440&feed=steam_community_announcements&headlines=0',"Na décima posição, Team Fortress 2 voltou a chamar atenção com o Scream Fortress XVIII. O evento de Halloween já está disponível e traz cinco mapas criados pela comunidade, uma nova caixa com vinte e três itens cosméticos, cinco novos taunts e vinte e um efeitos Unusual. É aquele tipo de atualização sazonal que sempre ressuscita o movimento do jogo e, em 2026, mostra de novo como TF2 continua vivo mesmo depois de tantos anos. Para quem gosta de eventos de Halloween, é uma das atualizações mais divertidas desta semana."),
    (9,'ps_plus_october','PS PLUS DE OUTUBRO','F1 25, HUNT E EARTH DEFENSE FORCE','https://blog.playstation.com/2026/09/30/playstation-plus-monthly-games-for-october-f1-25-hunt-showdown-1896-earth-defense-force-world-brothers-2/',"Na nona posição, a Sony confirmou os jogos mensais do PlayStation Plus para outubro. A seleção inclui F1 25, Hunt: Showdown 1896 e Earth Defense Force: World Brothers 2. É uma lista bem variada: corrida para quem quer velocidade, extração e combate tenso em Hunt, e ação cooperativa mais leve no universo de Earth Defense Force. Como esses jogos entram na rotação mensal, vale para quem já assina o serviço e estava procurando algo novo sem comprar outro título agora no começo do mês."),
    (8,'kingdom_hearts_switch2','KINGDOM HEARTS NO SWITCH 2','A COLEÇÃO I A III CHEGA EM 8 DE OUTUBRO','https://press.na.square-enix.com/SQUARE-ENIX-UNVEILS-NEW-KINGDOM-HEARTS-ANNOUNCEMENTS-DURING-NINTENDO-D',"Na oitava posição, Kingdom Hearts Collection de I a III está chegando ao Nintendo Switch 2 no dia oito de outubro. A coleção reúne HD 1.5 mais 2.5 ReMIX, HD 2.8 Final Chapter Prologue e Kingdom Hearts III com Re Mind. Para o Switch 2, o ponto mais importante é ter a saga principal reunida em uma versão nativa da nova plataforma, em vez de depender apenas da experiência em nuvem das versões anteriores. Para quem quer começar Kingdom Hearts ou revisitar a série antes do quarto jogo, esse lançamento chega em uma ótima hora."),
    (7,'cod_mw4','MODERN WARFARE 4 SE APROXIMA','NOVO CALL OF DUTY CHEGA EM 23 DE OUTUBRO','https://www.callofduty.com/br/pt/modernwarfare4',"Na sétima posição, Call of Duty: Modern Warfare 4 entra de vez no radar de outubro. O lançamento está marcado para vinte e três de outubro e a campanha coloca uma guerra de grande escala na Península Coreana, enquanto o Capitão Price trava sua própria batalha nas sombras. O jogo está confirmado para PlayStation 5, Xbox Series, PC e Nintendo Switch 2. Call of Duty sempre domina a conversa quando se aproxima do lançamento, e com poucas semanas restantes a tendência é vermos cada vez mais detalhes de campanha, multiplayer e conteúdo de lançamento."),
    (6,'ghost_yotei_complete','GHOST OF YŌTEI COMPLETE EDITION','EDIÇÃO COMPLETA JÁ CHEGOU AO PS5','https://blog.playstation.com/2026/08/12/ghost-of-yotei-complete-edition-comes-to-ps5-october-1/',"Na sexta posição, Ghost of Yōtei Complete Edition chegou ao PlayStation 5 em primeiro de outubro. A nova edição reúne o jogo e conteúdos adicionais em um pacote único e recoloca o título em destaque justamente na mesma semana em que a Sony anunciou o QSSR. Isso torna Ghost of Yōtei uma vitrine importante para o hardware atual do PS5, porque além do conteúdo completo ele também está entre os primeiros títulos escolhidos para demonstrar a nova tecnologia de reconstrução de imagem por inteligência artificial."),
    (5,'dragons_dogma_dark_arisen',"DRAGON'S DOGMA 2: DARK ARISEN",'EXPANSÃO CHEGA EM 9 DE OUTUBRO','https://www.capcom.co.jp/ir/english/news/html/e260610.html',"Na quinta posição, Dragon's Dogma 2: Dark Arisen está a poucos dias do lançamento, marcado para nove de outubro. A Capcom descreve o projeto como uma expansão paga que adiciona uma nova história e mais conteúdo ao RPG de ação lançado em 2024. A empresa também promete melhorias de acessibilidade e experiência com base no feedback dos jogadores. Outra novidade importante é a chegada ao Nintendo Switch 2, onde o jogo base e a expansão serão oferecidos juntos. Para fãs de RPG de mundo aberto, é um dos lançamentos mais fortes da próxima semana."),
    (4,'star_wars_galactic_racer','STAR WARS: GALACTIC RACER','CORRIDAS COMEÇAM EM 6 DE OUTUBRO','https://starwarsgalacticracer.com/news/official-gameplay-trailer/',"Na quarta posição, Star Wars: Galactic Racer está praticamente na largada. O jogo chega no dia seis de outubro para PlayStation 5, Xbox Series e PC. A proposta mergulha na cena de corridas clandestinas da galáxia, com landspeeders, speeder bikes, skim speeders e podracers. A campanha acompanha Shade, enquanto o multiplayer coloca os jogadores frente a frente por supremacia nas pistas. É uma combinação diferente dentro de Star Wars e chega com uma proposta clara: nada de Força ou profecia, aqui o foco é velocidade, estratégia e habilidade ao volante."),
    (3,'ace_combat_8','ACE COMBAT 8 JÁ DECOLOU','WINGS OF THEVE CHEGOU EM 2 DE OUTUBRO','https://www.bandainamcoent.com/news/ace-combat-8-wings-of-theve-takes-flight-today',"Na terceira posição, Ace Combat 8: Wings of Theve já está disponível. O novo capítulo foi lançado em dois de outubro para PlayStation 5, Xbox Series e PC e marca o retorno da linha principal da franquia depois de anos. O jogo aposta em combates aéreos cinematográficos, nuvens volumétricas e clima capaz de influenciar as missões. Também amplia bastante o online, com modos cooperativos e PvPvE. Depois de tanta expectativa, o foco agora muda para a recepção dos jogadores, desempenho e o quanto a Bandai Namco conseguiu evoluir a fórmula de Ace Combat."),
    (2,'qssr_ps5','PS5 GANHA UPSCALING POR IA','QSSR CHEGA AO CONSOLE BASE','https://blog.playstation.com/2026/10/01/ai-upscaling-is-coming-to-ps5/',"Na segunda posição, uma das notícias mais importantes da semana para quem joga no PS5: a Sony anunciou o QSSR, Quick Spectral Super Resolution. A tecnologia leva upscaling guiado por inteligência artificial ao PS5 padrão, usando uma arquitetura mais leve derivada do trabalho do Project Amethyst com a AMD. Marvel's Wolverine e Ghost of Yōtei são os primeiros jogos confirmados. A Sony também pretende disponibilizar a biblioteca a outros desenvolvedores. O PS5 comum não vira um PS5 Pro, mas ganha uma ferramenta nova para melhorar nitidez e estabilidade sem exigir o mesmo custo computacional do PSSR."),
    (1,'gears_eday','GEARS OF WAR: E-DAY É O #1','EARLY ACCESS JÁ COMEÇOU','https://news.xbox.com/en-us/2026/10/01/gears-of-war-e-day-early-access-launch-trailer-xbox/',"E na primeira posição está Gears of War: E-Day. O acesso antecipado começou em primeiro de outubro para jogadores elegíveis e o lançamento mundial acontece em seis de outubro. A Coalition trouxe um novo trailer de gameplay para marcar a chegada, enquanto o jogo volta ao passado para contar o Emergence Day, com Marcus Fenix e Dominic Santiago enfrentando o início da invasão Locust. Além da campanha, o pacote inclui multiplayer e Horde Siege. Entre franquia histórica, lançamento iminente e Game Pass no primeiro dia, Gears é hoje o assunto com maior peso no calendário de Xbox. Qual desses dez você quer ver em um vídeo completo?")
]

OUT.joinpath('auto-script.txt').write_text('\n\n'.join(x[5] for x in items) + '\n', encoding='utf-8')
blocked=['avatar','author','profile','headshot','newsletter','podcast','logo','icon','header','footer']
media=[]; scenes=[]
for rank,role,title,subtitle,source,text in items:
    if role == 'tf2_scream_fortress':
        media += [
            {'type':'video','steam_app_id':440,'role':role,'max_assets':1,'min_duration':6,'source_proof':source,'blocked_tokens':blocked},
            {'type':'image','steam_app_id':440,'role':role,'max_assets':2,'source_proof':source,'blocked_tokens':blocked},
        ]
    else:
        media += [
            {'type':'video','url':source,'role':role,'max_assets':1,'min_duration':6,'source_proof':source,'relevance_evidence':'official_topic_page_embedded_video','blocked_tokens':blocked},
            {'type':'image','url':source,'role':role,'max_assets':2,'allow_images_from_page':True,'source_proof':source,'relevance_evidence':'official_topic_page_image','blocked_tokens':blocked},
        ]
    scenes.append({'rank':rank,'role':role,'title':f'#{rank}  {title}','subtitle':subtitle,'media_indices':[]})

plan={'topic':'Top 10 Games de Hoje - 4 de outubro de 2026','minimum_assets':10,'minimum_video_assets':0,'minimum_unique_video_seconds':0,'minimum_image_assets':8,'media':media,'scenes':scenes}
OUT.joinpath('auto-media-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2),encoding='utf-8')
OUT.joinpath('selected.json').write_text(json.dumps({'editorial_title_ptbr':'Top 10 Games de Hoje: as maiores notícias de 4 de outubro','format':'top10_daily','items':[{'rank':x[0],'title':x[2],'source':x[4]} for x in items]},ensure_ascii=False,indent=2),encoding='utf-8')
OUT.joinpath('master-youtube.json').write_text(json.dumps({'title':'TOP 10 GAMES DE HOJE: as maiores notícias do dia!','description':'🎮 O Radar dos Games reúne em um único vídeo os 10 assuntos mais fortes do momento: Gears of War: E-Day, QSSR no PS5, Ace Combat 8, Star Wars: Galactic Racer, Dragon\'s Dogma 2: Dark Arisen e muito mais.\n\n#RadarDosGames #Games #PS5 #Xbox #NintendoSwitch2 #PCGaming','tags':['Radar dos Games','games','noticias games','top 10 games','Gears of War E-Day','PS5','QSSR','Ace Combat 8','Star Wars Galactic Racer','Dragon\'s Dogma 2'],'privacy':'unlisted','containsSyntheticMedia':False},ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'items':10,'format':'top10_daily'},ensure_ascii=False))
